package com.toonflow.controller;

import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.toonflow.common.exception.BusinessException;
import com.toonflow.common.result.R;
import com.toonflow.entity.OProject;
import com.toonflow.mapper.OProjectMapper;
import com.toonflow.ai.vendor.VendorService;
import com.toonflow.mapper.OAgentDeployMapper;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Data;
import lombok.RequiredArgsConstructor;
import org.apache.commons.io.FileUtils;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.web.bind.annotation.*;

import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.*;

@RestController
@RequestMapping("/api/project")
@RequiredArgsConstructor
public class ProjectController {

    private final OProjectMapper projectMapper;
    private final OAgentDeployMapper agentDeployMapper;
    private final VendorService vendorService;

    @Value("${toonflow.data-dir}")
    private String dataDir;

    @PostMapping("/getProject")
    public R<List<OProject>> getProject() {
        List<OProject> list = projectMapper.selectList(
                new LambdaQueryWrapper<OProject>().orderByDesc(OProject::getCreateTime));
        return R.ok(list);
    }

    @PostMapping("/addProject")
    public R<Map<String, String>> addProject(@Valid @RequestBody AddProjectRequest req) {
        OProject project = new OProject();
        // UUID will be auto-generated by MyBatis-Plus ASSIGN_UUID
        project.setProjectType(req.getProjectType());
        project.setName(req.getName());
        project.setIntro(req.getIntro());
        project.setType(req.getType());
        project.setArtStyle(req.getArtStyle());
        project.setDirectorManual(req.getDirectorManual());
        project.setVideoRatio(req.getVideoRatio());
        project.setImageModel(req.getImageModel());
        project.setVideoModel(req.getVideoModel());
        project.setImageQuality(req.getImageQuality());
        project.setMode(req.getMode());
        project.setUserId(1);
        project.setCreateTime(System.currentTimeMillis());
        projectMapper.insert(project);
        return R.ok(Map.of("message", "新增项目成功"));
    }

    @PostMapping("/editProject")
    public R<Map<String, String>> editProject(@Valid @RequestBody EditProjectRequest req) {
        OProject project = projectMapper.selectById(req.getId());
        if (project == null) throw new BusinessException("项目不存在");
        if (req.getName() != null) project.setName(req.getName());
        if (req.getIntro() != null) project.setIntro(req.getIntro());
        if (req.getType() != null) project.setType(req.getType());
        if (req.getArtStyle() != null) project.setArtStyle(req.getArtStyle());
        if (req.getDirectorManual() != null) project.setDirectorManual(req.getDirectorManual());
        if (req.getVideoRatio() != null) project.setVideoRatio(req.getVideoRatio());
        if (req.getImageModel() != null) project.setImageModel(req.getImageModel());
        if (req.getVideoModel() != null) project.setVideoModel(req.getVideoModel());
        if (req.getImageQuality() != null) project.setImageQuality(req.getImageQuality());
        if (req.getMode() != null) project.setMode(req.getMode());
        if (req.getProjectType() != null) project.setProjectType(req.getProjectType());
        projectMapper.updateById(project);
        return R.ok(Map.of("message", "编辑项目成功"));
    }

    @PostMapping("/delProject")
    public R<Map<String, String>> delProject(@RequestBody Map<String, Long> body) {
        Long id = body.get("id");
        if (id == null) throw new BusinessException("id不能为空");
        projectMapper.deleteById(id);
        return R.ok(Map.of("message", "删除项目成功"));
    }

    /**
     * 获取项目使用的 Agent 模型详情
     */
    @PostMapping("/getModelDetails")
    public R<Map<String, Object>> getModelDetails(@RequestBody Map<String, String> body) {
        String key = body.get("key"); // scriptAgent / productionAgent
        com.toonflow.entity.OAgentDeploy deploy = agentDeployMapper.selectOne(
                new com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<com.toonflow.entity.OAgentDeploy>()
                        .eq(com.toonflow.entity.OAgentDeploy::getKey, key).last("LIMIT 1"));
        if (deploy == null || deploy.getModelName() == null) throw new BusinessException("未找到模型");
        String[] parts = deploy.getModelName().split(":", 2);
        if (parts.length < 2) throw new BusinessException("模型名称格式错误");
        Map<String, Object> model = vendorService.getModelDetail(parts[0], parts[1]);
        return R.ok(model);
    }

    // ========== 视觉手册（Markdown 文件存储于 skills 目录）==========

    /**
     * Fix 1: return raw string content, not wrapped map.
     */
    @PostMapping("/visualManual")
    public R<String> visualManual(@RequestBody Map<String, String> body) {
        String type = body.get("type");
        Path base = Paths.get(dataDir, "skills", "art_skills", "chinese_sweet_romance");
        String content = "";
        try (java.util.stream.Stream<Path> stream = Files.walk(base)) {
            content = stream.filter(Files::isRegularFile)
                    .filter(p -> p.getFileName().toString().equals(type + ".md"))
                    .findFirst()
                    .map(p -> { try { return Files.readString(p, StandardCharsets.UTF_8); } catch (Exception e) { return ""; } })
                    .orElse("");
        } catch (Exception ignored) {}
        return R.ok(content);
    }

    /**
     * Fix 2: getVisualManual — items have { name, image, stylePath, data } (no directorManual).
     */
    @PostMapping("/getVisualManual")
    public R<List<Map<String, Object>>> getVisualManual() {
        return R.ok(readSkillDirs("art_skills", VISUAL_DATA_MAP, "stylePath"));
    }

    /**
     * Fix 3: queryDirectorManual — items have { name, image, directorManual, data } (no stylePath).
     */
    @PostMapping("/queryDirectorManual")
    public R<List<Map<String, Object>>> queryDirectorManual() {
        return R.ok(readSkillDirs("story_skills", DIRECTOR_DATA_MAP, "directorManual"));
    }

    /**
     * Fix 5: addVisualManual — write md files and images under skills/art_skills/{stylePath}/
     */
    @PostMapping("/addVisualManual")
    public R<Map<String, String>> addVisualManual(@RequestBody Map<String, Object> body) {
        saveManual(body, "art_skills", VISUAL_SUBDIR_MAP, false);
        return R.ok(Map.of("message", "视觉手册已保存"));
    }

    /**
     * Fix 6: addDirectorManual — write md files and images under skills/story_skills/{directorManual}/
     */
    @PostMapping("/addDirectorManual")
    public R<Map<String, String>> addDirectorManual(@RequestBody Map<String, Object> body) {
        saveManual(body, "story_skills", DIRECTOR_SUBDIR_MAP, false);
        return R.ok(Map.of("message", "导演手册已保存"));
    }

    /**
     * Fix 7: editVisualManual — overwrite existing files.
     */
    @PostMapping("/editVisualManual")
    public R<Map<String, String>> editVisualManual(@RequestBody Map<String, Object> body) {
        saveManual(body, "art_skills", VISUAL_SUBDIR_MAP, true);
        return R.ok(Map.of("message", "视觉手册已更新"));
    }

    /**
     * Fix 8: editDirectorlManual (note: original typo preserved in URL).
     */
    @PostMapping("/editDirectorlManual")
    public R<Map<String, String>> editDirectorlManual(@RequestBody Map<String, Object> body) {
        saveManual(body, "story_skills", DIRECTOR_SUBDIR_MAP, true);
        return R.ok(Map.of("message", "导演手册已更新"));
    }

    /**
     * Fix 9: deleteVisualManual — delete skills/art_skills/{name}/ recursively.
     */
    @PostMapping("/deleteVisualManual")
    public R<Map<String, String>> deleteVisualManual(@RequestBody Map<String, Object> body) {
        String name = (String) body.get("name");
        if (name == null || name.isBlank()) throw new BusinessException("name不能为空");
        validateName(name);
        Path dir = Paths.get(dataDir, "skills", "art_skills", name);
        deleteDirectory(dir);
        return R.ok(Map.of("message", "视觉手册已删除"));
    }

    /**
     * Fix 10: deleteDirectorManual — delete skills/story_skills/{name}/ recursively.
     */
    @PostMapping("/deleteDirectorManual")
    public R<Map<String, String>> deleteDirectorManual(@RequestBody Map<String, Object> body) {
        String name = (String) body.get("name");
        if (name == null || name.isBlank()) throw new BusinessException("name不能为空");
        validateName(name);
        Path dir = Paths.get(dataDir, "skills", "story_skills", name);
        deleteDirectory(dir);
        return R.ok(Map.of("message", "导演手册已删除"));
    }

    // ========== helpers ==========

    // [label, value, subDir]  subDir="" means at style dir root
    private static final List<String[]> VISUAL_DATA_MAP = List.of(
            new String[]{"README", "README", ""},
            new String[]{"前缀", "prefix", ""},
            new String[]{"角色", "art_character", "art_prompt"},
            new String[]{"角色衍生", "art_character_derivative", "art_prompt"},
            new String[]{"道具", "art_prop", "art_prompt"},
            new String[]{"道具衍生", "art_prop_derivative", "art_prompt"},
            new String[]{"场景", "art_scene", "art_prompt"},
            new String[]{"场景衍生", "art_scene_derivative", "art_prompt"},
            new String[]{"分镜", "director_storyboard", "driector_skills"},
            new String[]{"分镜视频", "art_storyboard_video", "art_prompt"},
            new String[]{"技法-导演规划", "director_planning_style", "driector_skills"},
            new String[]{"技法-分镜表设计", "director_storyboard_table_style", "driector_skills"});

    private static final List<String[]> DIRECTOR_DATA_MAP = List.of(
            new String[]{"README", "README", ""},
            new String[]{"导演规划", "director_planning_narrative", "driector_skills"},
            new String[]{"分镜表", "director_storyboard_table_narrative", "driector_skills"});

    // value -> subDir map for visual manual
    private static final Map<String, String> VISUAL_SUBDIR_MAP;
    // value -> subDir map for director manual
    private static final Map<String, String> DIRECTOR_SUBDIR_MAP;

    static {
        Map<String, String> vm = new LinkedHashMap<>();
        for (String[] e : VISUAL_DATA_MAP) vm.put(e[1], e[2]);
        VISUAL_SUBDIR_MAP = Collections.unmodifiableMap(vm);

        Map<String, String> dm = new LinkedHashMap<>();
        for (String[] e : DIRECTOR_DATA_MAP) dm.put(e[1], e[2]);
        DIRECTOR_SUBDIR_MAP = Collections.unmodifiableMap(dm);
    }

    /**
     * Read skill directories and build result list.
     * @param dirFieldName either "stylePath" or "directorManual"
     */
    private List<Map<String, Object>> readSkillDirs(String skillsSubDir, List<String[]> dataMap, String dirFieldName) {
        Path skillsRoot = Paths.get(dataDir, "skills", skillsSubDir);
        List<Map<String, Object>> result = new java.util.ArrayList<>();
        if (!Files.exists(skillsRoot)) return result;
        try (java.util.stream.Stream<Path> stream = Files.list(skillsRoot)) {
            List<Path> dirs = stream.filter(Files::isDirectory).sorted().toList();
            for (Path styleDir : dirs) {
                String dirName = styleDir.getFileName().toString();
                // Read README first line as name
                Path readmePath = styleDir.resolve("README.md");
                String name = dirName;
                if (Files.exists(readmePath)) {
                    try {
                        String first = Files.readString(readmePath, StandardCharsets.UTF_8)
                                .lines().findFirst().orElse("").replace("--", "").trim();
                        if (!first.isEmpty()) name = first;
                    } catch (Exception ignored) {}
                }
                // Collect images
                Path imagesDir = styleDir.resolve("images");
                List<String> images = new java.util.ArrayList<>();
                if (Files.exists(imagesDir)) {
                    try (java.util.stream.Stream<Path> imgStream = Files.list(imagesDir)) {
                        imgStream.filter(p -> p.getFileName().toString().matches("(?i).*\\.(png|jpe?g|gif|webp|svg)"))
                                .map(p -> "/" + skillsSubDir + "/" + dirName + "/images/" + p.getFileName())
                                .forEach(images::add);
                    } catch (Exception ignored) {}
                }
                // Read each md field
                List<Map<String, String>> data = new java.util.ArrayList<>();
                for (String[] entry : dataMap) {
                    String label = entry[0], value = entry[1], subDir = entry[2];
                    Path mdPath = subDir.isEmpty()
                            ? styleDir.resolve(value + ".md")
                            : styleDir.resolve(subDir).resolve(value + ".md");
                    String content = "";
                    if (Files.exists(mdPath)) {
                        try { content = Files.readString(mdPath, StandardCharsets.UTF_8); }
                        catch (Exception ignored) {}
                    }
                    Map<String, String> d = new java.util.HashMap<>();
                    d.put("label", label);
                    d.put("value", value);
                    d.put("data", content);
                    data.add(d);
                }
                Map<String, Object> item = new java.util.HashMap<>();
                item.put("name", name);
                item.put("image", images);
                item.put(dirFieldName, dirName);  // only one of stylePath or directorManual
                item.put("data", data);
                result.add(item);
            }
        } catch (Exception e) {
            throw new BusinessException("读取手册失败: " + e.getMessage());
        }
        return result;
    }

    /**
     * Shared logic for add/edit visual and director manuals.
     * For visual: pathKey="stylePath", skillsSubDir="art_skills"
     * For director: pathKey="directorManual", skillsSubDir="story_skills"
     */
    @SuppressWarnings("unchecked")
    private void saveManual(Map<String, Object> body, String skillsSubDir,
                            Map<String, String> subdirMap, boolean editMode) {
        String name = (String) body.get("name");
        if (name == null || name.isBlank()) throw new BusinessException("name不能为空");
        validateName(name);

        // For visual: stylePath; for director: directorManual
        String pathKey = skillsSubDir.equals("art_skills") ? "stylePath" : "directorManual";
        String dirKey = body.containsKey(pathKey) ? (String) body.get(pathKey) : name;
        if (dirKey == null || dirKey.isBlank()) dirKey = name;

        Path mainPath = Paths.get(dataDir, "skills", skillsSubDir, dirKey);

        if (!editMode && Files.exists(mainPath)) {
            throw new BusinessException("请勿填写重复名称的手册");
        }
        if (editMode && !Files.exists(mainPath)) {
            throw new BusinessException("手册不存在");
        }

        // Write md files
        List<Map<String, Object>> data = (List<Map<String, Object>>) body.get("data");
        if (data != null) {
            Set<String> validKeys = subdirMap.keySet();
            for (Map<String, Object> item : data) {
                String value = (String) item.get("value");
                String content = (String) item.get("data");
                if (value == null || !validKeys.contains(value)) continue;
                if (content == null) content = "";
                String subDir = subdirMap.get(value);
                Path fileDir = (subDir == null || subDir.isEmpty()) ? mainPath : mainPath.resolve(subDir);
                Path filePath = fileDir.resolve(value + ".md");
                // For README prepend name (matches original editVisualManual/editDirectorlManual behavior)
                String fileContent = (editMode && "README".equals(value)) ? name + "\n" + content : content;
                try {
                    Files.createDirectories(fileDir);
                    Files.writeString(filePath, fileContent, StandardCharsets.UTF_8);
                } catch (Exception e) {
                    throw new BusinessException("写入文件失败: " + e.getMessage());
                }
            }
        }

        // Handle images: images is List<String> where each entry is either a URL (http) or base64
        List<String> images = (List<String>) body.get("images");
        if (images == null) images = List.of();

        Path imagesDir = mainPath.resolve("images");

        // Delete images not retained (those starting with http are retained by filename)
        if (Files.exists(imagesDir)) {
            Set<String> retainedNames = new LinkedHashSet<>();
            for (String img : images) {
                if (img.startsWith("http")) {
                    try {
                        String fileName = Paths.get(new java.net.URI(img).getPath()).getFileName().toString();
                        retainedNames.add(fileName);
                    } catch (Exception ignored) {}
                }
            }
            try (java.util.stream.Stream<Path> imgStream = Files.list(imagesDir)) {
                List<Path> existing = imgStream
                        .filter(p -> p.getFileName().toString().matches("(?i).*\\.(png|jpe?g|gif|webp|svg)"))
                        .toList();
                for (Path f : existing) {
                    if (!retainedNames.contains(f.getFileName().toString())) {
                        try { Files.deleteIfExists(f); } catch (Exception ignored) {}
                    }
                }
            } catch (Exception ignored) {}
        }

        // Write new base64 images
        try {
            Files.createDirectories(imagesDir);
        } catch (Exception e) {
            throw new BusinessException("创建图片目录失败: " + e.getMessage());
        }
        for (String img : images) {
            if (!img.startsWith("http")) {
                try {
                    String b64 = img.replaceFirst("^data:[^;]+;base64,", "");
                    byte[] bytes = Base64.getDecoder().decode(b64);
                    String fileName = UUID.randomUUID().toString().replace("-", "") + ".jpg";
                    Files.write(imagesDir.resolve(fileName), bytes);
                } catch (Exception e) {
                    throw new BusinessException("保存图片失败: " + e.getMessage());
                }
            }
        }
    }

    private void validateName(String name) {
        if (name.contains("/") || name.contains("\\") || ".".equals(name) || "..".equals(name)
                || name.matches("^\\d+$")) {
            throw new BusinessException("名称不能包含路径分隔符或为纯数字");
        }
    }

    private void deleteDirectory(Path dir) {
        try {
            FileUtils.deleteDirectory(dir.toFile());
        } catch (Exception e) {
            // Ignore if directory doesn't exist, otherwise rethrow
            if (dir.toFile().exists()) {
                throw new BusinessException("删除目录失败: " + e.getMessage());
            }
        }
    }

    @Data
    public static class AddProjectRequest {
        @NotBlank private String projectType;
        @NotBlank private String name;
        @NotNull private String intro;
        @NotBlank private String type;
        @NotNull private String artStyle;
        @NotNull private String directorManual;
        @NotNull private String videoRatio;
        @NotNull private String imageModel;
        @NotNull private String videoModel;
        @NotNull private String imageQuality;
        @NotNull private String mode;
    }

    @Data
    public static class EditProjectRequest {
        @NotNull private Long id;
        private String name;
        private String intro;
        private String type;
        private String artStyle;
        private String directorManual;
        private String videoRatio;
        private String imageModel;
        private String videoModel;
        private String imageQuality;
        private String mode;
        private String projectType;
    }
}
